routes/web.php
Route::get('cr_assin','AssignInController@cr_assin');
Route::get('des_assin','AssignInController@des_assin');
Route::get('pat_assin','AssignInController@pat_assin');
Route::get('trass/in/{id}','TrAssInController@tr_index');
Route::post('trass/in/save','TrAssInController@tr_save');
Route::get('asin/{id}','TrAssInController@tr_edit');
Route::post('asin/save/{id}','TrAssInController@tr_edit_save');
Route::get('trass/out/{id}','TradAssOutController@tr_index');
Route::post('trass/out/save','TradAssOutController@tr_save');
Route::get('asout/{id}','TradAssOutController@tr_edit');
Route::post('asout/save/{id}','TradAssOutController@tr_edit_save');
Route::resource('leads','LeadController');
Route::get('lead_gen','leadGenController@create');
Route::post('lead_save','leadGenController@save');
Route::resource('country','CountryController');
Route::resource('state','StateController');
Route::get('/findstate','ChildController@findStates');
Route::get('/findcity','ChildController@findcity');
Route::get('/findprod','ChildController@findprod');
Route::get('/trademark/update_status/edit/{id}','FrontEndController@edit_status');
Route::post('edit/status/submit','AddTradmarkController@update_insert_status');
Route::get('images/{image}/delete/{id}','DeleteImageController@tradeimg');
Route::get('imagess/{image}/delete/{id}','DeleteImageController@tradestate');
Route::get('imagesss/{image}/delete/{id}','DeleteImageController@tradeslogo');
Route::get('images/delete/{image}/{id}','DeleteImageController@updateImg');
Route::get('imagesh/delete/{image}/{id}','DeleteImageController@updateImgh');
Route::get('update_status/delete/{id}','DeleteListController@trade_status');
Route::get('imagesc/delete/{image}/{id}','DeleteImageController@copyimg');
Route::get('imagesc/deletec/{image}/{id}','DeleteImageController@copyimgd');
Route::get('imagesc/deleteca/{image}/{id}','DeleteImageController@copyimgda');
Route::get('imaged/delete/{image}/{id}','DeleteImageController@designimgda');
Route::get('imagesd/delete/{image}/{id}','DeleteImageController@designimgdas');
Route::get('imagesds/delete/{image}/{id}','DeleteImageController@designimgdass');
Route::get('imagesdsd/delete/{image}/{id}','DeleteImageController@designimgdassd');
Route::get('imagi/delete/{image}/{id}','DeleteImageController@investimg');
Route::get('design/images/delete/{image}/{id}','DeleteImageController@designimgd');
Route::get('designcor/images/delete/{image}/{id}','DeleteImageController@designimgcor');
Route::get('copy/delete/{image}/{id}','DeleteImageController@cuimg');
Route::get('enf/delete/{image}/{id}','DeleteImageController@enfimg');
Route::get('branddashboard','DashboardController@brand');
Route::get('designdashboard','DashboardController@design');
Route::get('copydashboard','DashboardController@copy');
Route::get('patentdashboard','DashboardController@patent');
Route::get('litidashboard','DashboardController@liti');
Route::get('trad_master','MasterController@trade');
Route::get('common_master','MasterController@common');
Route::get('patent_master','MasterController@patent');
Route::get('brand_master','MasterController@brand');
Route::get('copy_master','MasterController@copy');
Route::get('notice/delete/{image}/{id}','DeleteImageController@noticeimg');
Route::get('/summary/hearing/{id}','HearingController@hearing');
Route::get('/summary/documents/{id}','LitiDocController@index');
Route::get('/summary/fees/{id}','FessController@index');
Route::get('summary/completion/{id}','CompletionController@comple');
Route::get('counsel-fees/{id}','FessController@counsel');
Route::post('counsel_fees/submit','FessController@save');
Route::get('summary/counsel-fee/edit/{id}','FessController@edit');
Route::post('counsel_fees_edit/submit','FessController@edit_save');
Route::get('delete/counsel/{image}/{id}','DeleteImageController@counsel');
Route::get('counsel-paid-fees/{id}','FessController@counsel_paid');
Route::get('counsel/paid_fees/{id}','FessController@counsel_paid_fee');
Route::post('counsel_paid_fees/submit','FessController@counsel_save_fee');
Route::get('counsel-paid-fees/edit/{id}','FessController@counsel_paid_edit');
Route::get('/delete/paid_fess/{image}/{id}','DeleteImageController@paid_fees');
Route::post('counsel_paid_fees_edit/submit/{id}','FessController@counsel_paid_save');
Route::get('advocate-fees/{id}','FessController@advocate');
Route::post('adv_fees/submit','FessController@adv_save');
Route::get('summary/advocate-fee/edit/{id}','FessController@adv_edit');
Route::get('delete/advocate/{image}/{id}','DeleteImageController@advocate');
Route::post('advocate_fees_edit/submit','FessController@adv_edit_save');
Route::get('advocate-paid-fees/{id}','FessController@advocate_paid');
Route::get('advocate/paid_fees/{id}','FessController@advocate_paid_fee');
Route::post('advocate_paid_fees/submit','FessController@advocate_save_fee');
Route::get('advocate-paid-fees/edit/{id}','FessController@advocate_paid_edit');
Route::post('advocate_paid_fees_edit/submit/{id}','FessController@advocate_paid_save');
Route::get('/delete/paid_fess/adv/{image}/{id}','DeleteImageController@adv_paid_fees');
Route::get('delete/liti-doc/{id}','LitiDocController@delete');
Route::get('delete/hearing/{id}','HearingController@delete');
Route::get('delete/expin/{image}/{id}','DeleteImageController@expins');
Route::get('delete/expens/{image}/{id}','DeleteImageController@expens');
Route::get('lead_home','leadGenController@show');
Route::get('leads-assign/{id}','LeadController@assign');
Route::post('assign-to/save','LeadController@save_ass');
Route::get('assign-to/{id}','LeadController@view_ass');
Route::get('forward-investigation/{id}','LeadController@invest_create');
Route::post('investc/save','LeadController@investsave');
Route::get('convert_to/{id}','LitigationNoticesController@convert');
Route::post('save/litigationc/{id}','LitigationNoticesController@save_convert');
Route::get('notices/delete/{id}','LitigationNoticesController@deleten');
Route::get('summary/delete/{id}','LitigationSummaryController@deletes');
Route::resource('/appff','ApplicatIionFieldssController');
Route::get('/fir/{id}/edit','AddBrandController@fir_edit');
Route::post('fir/update/{id}','AddBrandController@update_fir');
Route::get('design/{id}/representation','DesignController@represantion');
Route::post('design/represnt/{id}','DesignController@represantion_save');
Route::get('/design/{id}/registration_certificate','DesignController@registration');
Route::post('design/regist/{id}','DesignController@regis_save');
Route::get('/design/{image}/delete/{id}','DeleteImageController@regis_des');
Route::post('roc_save/{id}','Copyright_roc_Controller@save');
Route::get('reg_cert/edit/{id}','Copyright_roc_Controller@edit');
Route::get('delete/cert/{image}/image/{id}','DeleteImageController@reg_cert');
Route::post('roc_save/edit/{id}','Copyright_roc_Controller@edit_save');
Route::get('notice-status/edit/{id}','NoticeStatController@edit');
Route::get('notice-status/edit/{image}/{id}','DeleteImageController@noticeimgst');
Route::post('notsta/edit/submit/{id}','NoticeStatController@update');
Route::get('delete/litiimg/{image}/{id}','DeleteImageController@litihear');
Route::get('edit-completion/{id}','CompletionController@edit');
Route::resource('/cities','CitiesController');
Route::get('/draft','DraftController@index');
Route::resource('/brand-product','BrandProductController');
Route::get('/copyright-draft','CopyrightDraftController@Draft');
Route::get('delete/poa/{image}/{id}','DeleteImageController@poa');
Route::get('copyright-fee/{id}','CopyAgentFeeController@create');
Route::post('save/agent-fee/{id}','CopyAgentFeeController@store');
Route::get('copyright-fee/edit/{id}','CopyAgentFeeController@edit');
Route::post('update/agent-fee/{id}','CopyAgentFeeController@update');
Route::get('delete/copy-fee/{image}/{id}','DeleteImageController@copy_invoice');
Route::get('delete/copy-fee/stamp/{image}/{id}','DeleteImageController@copy_stamp');
Route::resource('design-draft','DesignDraftController');
Route::get('design-fee/{id}','DesignAgentController@create');
Route::post('design/save/agent-fee/{id}','DesignAgentController@store');
Route::get('design-fee/edit/{id}','DesignAgentController@edit');
Route::post('design/update/agent-fee/{id}','DesignAgentController@update');
Route::get('delete/des-fee/{image}/{id}','DeleteImageController@des_invoice');
Route::get('delete/des-fee/stamp/{image}/{id}','DeleteImageController@des_stamp');
Route::get('delete/msme/{image}/{id}','DeleteImageController@msme');
Route::get('delete/trad/poa/{image}/{id}','DeleteImageController@trad_poa');
Route::get('trade-fee/{id}','TradAgentFeeController@create');
Route::post('trade/save/agent-fee/{id}','TradAgentFeeController@store');
Route::get('trade-fee/edit/{id}','TradAgentFeeController@edit');
Route::post('trade/update/agent-fee/{id}','TradAgentFeeController@update');
Route::get('delete/trade-fee/{image}/{id}','DeleteImageController@trade_invoice');
Route::get('delete/trade-fee/stamp/{image}/{id}','DeleteImageController@trade_stamp');
Route::get('assign-to','LeadController@assign_to');
Route::get('/testing','TestingController@index');
Route::resource('/factsheet','FactSheetController');
Route::get('/edit_factsheet/{id}', 'FactSheetController@edit');
Route::post('/factsheet/update', 'FactSheetController@update');
Route::get('/factsheet/{id}/show', 'FactSheetController@show_factsheet');
Route::post('/factsheet/delete', 'FactSheetController@factSheetDelete');
Route::post('/factsheet/approval_process', 'FactSheetController@factSheetApprovalProcess');
Route::get('/fsa/{id}', 'FactSheetController@factSheetInitiatorAp');
Route::post('/factsheetstatusshared', 'FactSheetController@factSheetStatusShared');
Route::get('/shared_success', 'FactSheetController@factSheetStatusSharedSuccess');

Route::get ( 'email', function () {
	Mail::send ( [ ], [ ], function ($message) {

app/BrandProduct.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class BrandProduct extends Model
{
    public function ent()
    {
        return $this->belongsTo(Entity::class);
    }
}

app/Http/Controllers/BrandProductController.php
<?php

namespace App\Http\Controllers;

use App\BrandProduct;
use App\Entity;
use Illuminate\Http\Request;
use Auth;
use Session;
class BrandProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        $posts = BrandProduct::orderBy('id','DESC')->get();
        return view('brandproduct.index',compact('posts'))->with('no',1);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $ents = Entity::all();
        $ar1 = [];
        foreach ($ents as $ent) {
            $ar1[$ent->id] = $ent->name;
        }
        return view('brandproduct.create',compact('ar1'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request ,array(
            'name' => 'required |unique:brand_products,name'
        ));

        $post = new BrandProduct();
        $post->name = $request->name;
        $post->ent_id = $request->ent_id;
        $post->save();
        Session::flash('success','Product Added!');
        return redirect()->route('brand-product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = BrandProduct::find($id);
        $ents = Entity::all();
        $ar1 = [];
        foreach ($ents as $ent) {
            $ar1[$ent->id] = $ent->name;
        }
        return view('brandproduct.edit',compact('post','ar1'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request ,array(
            'name' => 'required |unique:brand_products,name,'.$id,
        ));

        $post = BrandProduct::find($id);
        $post->name = $request->name;
        $post->ent_id = $request->ent_id;
        $post->save();
        Session::flash('success','Product Updated!');
        return redirect()->route('brand-product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/brandproduct/create.blade.php
@include('include.header')
    <style>
        .card{
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        }
    </style>
    <div class="page-wrapper">
        <div class="container-fluid">
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h4 class="text-themecolor">Products | <a href="{{ route('brand-product.index') }}" >Go Back <i class="fa fa-arrow-circle-left"></i></a> </h4>
                </div>
                <div class="col-md-7 align-self-center text-right">
                    <div class="d-flex justify-content-end align-items-center">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{action('FrontEndController@index')}}">Home</a></li>
                            <li class="breadcrumb-item active">Products</li>
                        </ol>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            @include('include.message')
                            {!! Form::open(['route' => 'brand-product.store','method' => 'POST','data-parsley-validate' => '']) !!}
                                <div class="row">
                                    <div class="col-md-6 form-group">
                                        {!! Form::label('name', 'Product Name:') !!}
                                        {!! Form::text('name', null, ['class' => 'form-control','required' => '']) !!}
                                    </div>
                                    <div class="col-md-6 form-group">
                                        {!! Form::label('ent_id', 'Entity Name:') !!}
                                        {!! Form::select('ent_id', $ar1, null, ['class' => 'form-control','required' => '','placeholder' => 'Select Entity']) !!}
                                    </div>
                                    <div class="col-md-12 text-center form-group">
                                        {!! Form::submit('submit', ['class' => 'btn btn-success']) !!}
                                    </div>
                                </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@include('include.footer')

resources/views/brandproduct/edit.blade.php
@include('include.header')
    <style>
        .card{
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        }
    </style>
    <div class="page-wrapper">
        <div class="container-fluid">
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h4 class="text-themecolor">Products | <a href="{{ route('brand-product.index') }}" >Go Back <i class="fa fa-arrow-circle-left"></i></a> </h4>
                </div>
                <div class="col-md-7 align-self-center text-right">
                    <div class="d-flex justify-content-end align-items-center">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{action('FrontEndController@index')}}">Home</a></li>
                            <li class="breadcrumb-item active">Products</li>
                        </ol>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            @include('include.message')
                            {!! Form::model($post,['route' => ['brand-product.update',$post->id],'method' => 'PUT','data-parsley-validate' => '']) !!}
                                <div class="row">
                                    <div class="col-md-6 form-group">
                                        {!! Form::label('name', 'Product Name:') !!}
                                        {!! Form::text('name', null, ['class' => 'form-control','required' => '']) !!}
                                    </div>
                                    <div class="col-md-6 form-group">
                                        {!! Form::label('ent_id', 'Entity Name:') !!}
                                        {!! Form::select('ent_id', $ar1, null, ['class' => 'form-control','required' => '','placeholder' => 'Select Entity']) !!}
                                    </div>
                                    <div class="col-md-12 text-center form-group">
                                        {!! Form::submit('submit', ['class' => 'btn btn-success']) !!}
                                    </div>
                                </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@include('include.footer')

resources/views/brandproduct/index.blade.php
@include('include.header')
    <style>
        .card{
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        }
    </style>
    <div class="page-wrapper">
        <div class="container-fluid">
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h4 class="text-themecolor">Products | <a href="{{ url('brand_master') }}" >Go Back <i class="fa fa-arrow-circle-left"></i></a> </h4>
                </div>
                <div class="col-md-7 align-self-center text-right">
                    <div class="d-flex justify-content-end align-items-center">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{action('FrontEndController@index')}}">Home</a></li>
                            <li class="breadcrumb-item active">Products</li>
                        </ol>
                        <a  href="{{ route('brand-product.create') }}" class="btn btn-info d-none d-lg-block m-l-15"><i class="fa fa-plus-circle"></i> Add</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            @include('include.message')
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Name</th>
                                            <th>Entity</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($posts as $item)
                                            <tr>
                                                <td>{{ $no++ }}</td>
                                                <td>{{ $item->name }}</td>
                                                <td>{{ $item->ent->name }}</td>
                                                <td>
                                                    <a href="{{ route('brand-product.edit',$item->id) }}" class="btn btn-sm btn-success">Edit</a>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@include('include.footer')