routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\AddBrandController;
use App\Http\Controllers\DeleteImageController;
use App\Http\Controllers\FessController;
use App\Http\Controllers\PatentController;
use App\LitigationNotice;

Route::resource('agency','AgencyController');

Route::get('/tests','AddBrandController@testss');
Route::get('/analytics','AddBrandController@Analytics');

Route::get('/design/show', 'DesignController@index');
Route::post('/design/save', 'DesignController@store');
Route::get('/design/create', 'DesignController@Create');
Route::get('/design/{id}/edit','DesignController@edit');
Route::post('/design/update_e/{id}','DesignController@update');
Route::get('/design/{id}/view', 'DesignController@view');
Route::get('design/{id}/update_status', 'Update_Status_Design_Controller@status_create');
Route::post('/design/status/submit', 'Update_Status_Design_Controller@submit');
Route::get('/design/license_in/{id}','Design_lic_in_Controller@license_create');
Route::post('/license_in/save/design', 'Design_lic_in_Controller@store');

Route::get('/design/license_in/edit/{id}','Design_lic_in_Controller@license_edit');
Route::post('/license_in/save/design/{id}', 'Design_lic_in_Controller@update');

Route::get('/design/license_out/{id}','Design_lic_out_Controller@license_create');
Route::post('/license_out/save/design', 'Design_lic_out_Controller@store');

Route::get('/design/license_out/edit/{id}','Design_lic_out_Controller@license_edit');
Route::post('/license_out/save/design/{id}', 'Design_lic_out_Controller@update');

Route::get('/design/assign_in/{id}','Design_ass_in_Controller@assign_create');
Route::post('/assign_in/save/design', 'Design_ass_in_Controller@store');
Route::get('/design/assign_in/edit/{id}','Design_ass_in_Controller@assign_edit');
Route::post('/assign_in/save/design/{id}', 'Design_ass_in_Controller@update');

Route::get('/design/assign_out/{id}','Design_ass_out_Controller@assign_create');
Route::post('/assign_out/save/design', 'Design_ass_out_Controller@store');

Route::get('/design/assign_out/edit/{id}','Design_ass_out_Controller@assign_edit');
Route::post('/assign_out/save/design/edit/{id}', 'Design_ass_out_Controller@update');

Route::post('/design/show', 'DesignController@search');
Route::get('design/update_status/edit/{id}','DesignController@edit_status');
Route::post('/design/edit_status/submit','DesignController@edit_status_save');

// Copyright

Route::resource('copyrights', 'CopyrightController');
Route::post('copyright/update/{id}',['uses' =>'CopyrightController@update','as' => 'copyrights.update']);
Route::post('copyrights/store',['uses' =>'CopyrightController@store','as' => 'copyrights.store']);
Route::get('/copyright/{id}/update_status', 'update_status_copyrightController@status_create');
Route::post('/copyright/status/submit', 'update_status_copyrightController@submit');
Route::get('/copyright/license_in/{id}','Copyright_lic_in_Controller@license_create');
Route::post('/license_in/save', 'Copyright_lic_in_Controller@store');

Route::get('/copyright/license_in/edit/{id}','Copyright_lic_in_Controller@license_edit');
Route::post('/license_in/save/{id}', 'Copyright_lic_in_Controller@update');

Route::get('/copyright/license_out/{id}','Copyright_lic_out_Controller@license_create');
Route::post('/license_out/save', 'Copyright_lic_out_Controller@store');

Route::get('/copyright/license_out/edit/{id}','Copyright_lic_out_Controller@license_edit');
Route::post('/license_out/save/{id}', 'Copyright_lic_out_Controller@update');

Route::get('/copyright/assign_in/{id}','Copyright_ass_in_Controller@assign_create');
Route::post('/assign_in/save', 'Copyright_ass_in_Controller@store');
Route::get('/copyright/assign_in/edit/{id}','Copyright_ass_in_Controller@assign_edit');
Route::post('/assign_in/save/{id}', 'Copyright_ass_in_Controller@update');
Route::get('/copyright/assign_out/{id}','Copyright_ass_out_Controller@assign_create');
Route::post('/assign_out/save', 'Copyright_ass_out_Controller@store');
Route::get('/copyright/assign_out/edit/{id}','Copyright_ass_out_Controller@assign_edit');
Route::post('/assign_out/save/{id}', 'Copyright_ass_out_Controller@edit_update');
Route::get('/copyright/{id}/registration_certificate','Copyright_roc_Controller@roc_create');
Route::post('copyrights', 'CopyrightController@search');
Route::get('copyright/edit/update_status/{id}','CopyrightController@update_status_create');
Route::post('copyright/edit_status/submit','CopyrightController@update_status_save');


Route::get('/patent/show', 'PatentController@index');
Route::get('/patent/create', 'PatentController@Create');
Route::get('/patent/edit/{id}', 'PatentController@edit');
Route::post('/patent/submit','PatentController@store');
Route::post('/patent/edit/save','PatentController@update');
Route::get('/patent/view/{id}','PatentController@show');

Route::post('/patent/show', 'PatentController@search');

Route::get('/patent/update_status/{id}','PatentController@update_s');
Route::post('/patent/save/status','PatentController@save_status');

Route::get('/patent/license_in/{id}','PatentLicInController@create');
Route::post('/patent/license_in/save','PatentLicInController@store');

Route::get('/patent/license_in/edit/{id}','PatentLicInController@edit');
Route::post('/patent/license_in/save/{id}','PatentLicInController@update');

Route::get('/patent/license_out/{id}','PatentLicOutController@create');
Route::post('/patent/license_out/save','PatentLicOutController@store');

Route::get('/patent/license_out/edit/{id}','PatentLicOutController@edit');
Route::post('/patent/license_out/save/{id}','PatentLicOutController@update');

Route::get('/patent/assign_in/{id}','PatentAssInController@create');
Route::post('/patent/assign_in/save','PatentAssInController@store');

Route::get('/patent/assign_in/edit/{id}','PatentAssInController@edit');
Route::post('/patent/assign_in/save/edit/{id}','PatentAssInController@update');

Route::get('/patent/assign_out/{id}','PatentAssOutController@create');
Route::post('/patent/assign_out/save','PatentAssOutController@store');

Route::get('/patent/assign_out/edit/{id}','PatentAssOutController@edit');
Route::post('/patent/assign_out/save/{id}','PatentAssOutController@update');

Route::resource('applicant_category','CategoryApplicantController');

Route::get('/invest/show', 'AddBrandController@InvestShow');
Route::post('/invest/show', 'AddBrandController@search');
Route::get('/invest/create', 'AddBrandController@InvestCreate');
Route::post('/invest/save', 'AddBrandController@InvestSave');
Route::get('/edit_inv/{id}', 'AddBrandController@EditInv');
Route::post('/invest/update', 'AddBrandController@InvestUpdate');
Route::get('/expensein/{id}/expenses', 'AddBrandController@expensesin');
Route::post('expensein/submit', 'AddBrandController@expensave');
Route::get('/expensein/{id}/edit','AddBrandController@expeins_edit');
Route::post('expensein/edit/submit','AddBrandController@expeins_save');

Route::get('show_inv/{id}','AddBrandController@show_all');
Route::get('/show/all','AddBrandController@viewall');

Route::get('/view_enforce/{id}','AddBrandController@EnforceView');
Route::get('/enforce/show', 'AddBrandController@EnforceShow');
Route::post('/enforce/show', 'AddBrandController@searche');
Route::get('/enforce/create', 'AddBrandController@EnforceCreate');
Route::post('/enforce/save','AddBrandController@EnforceSave');
Route::get('/edit_enforce/{id}', 'AddBrandController@EditEnf');
Route::post('/enforce/update', 'AddBrandController@EnforceUpdate');
Route::get('/expensen/{id}/expenses', 'AddBrandController@expensesen');
Route::post('expensen/submit', 'AddBrandController@expenesave');
Route::get('/expensen/{id}/edit','AddBrandController@expens_edit');
Route::post('expensen/edit/submit','AddBrandController@expens_save');
Route::get('/fir_details/{id}', 'AddBrandController@Fir');
Route::post('/fir/submit','AddBrandController@FirSave');

Route::get('/targets/show', 'AddBrandController@TargetsShow');
Route::get('/targets/create', 'AddBrandController@TargetsCreate');
Route::post('/targets/save', 'AddBrandController@TargetsSave');
Route::get('edit/{id}/target', 'AddBrandController@TargetsEdit');
Route::post('/targets/update', 'AddBrandController@TargetsUpdate');

Route::get('/state/show', 'AddBrandController@state');
Route::get('/state/create', 'AddBrandController@stateCreate');
Route::post('/state/save', 'AddBrandController@stateSave');
Route::get('edit/{id}/state', 'AddBrandController@stateEdit');
Route::post('/state/update', 'AddBrandController@stateUpdate');


Route::get('/city/show', 'AddBrandController@city');
Route::get('/city/create', 'AddBrandController@cityCreate');
Route::post('/city/save', 'AddBrandController@citySave');
Route::get('edit/{id}/city', 'AddBrandController@cityEdit');
Route::post('/city/update', 'AddBrandController@cityUpdate');

Route::get('/', 'FrontEndController@index');
Route::get('/dashbord', 'FrontEndController@index');
Route::get('/tm_portfolio', 'FrontEndController@tradmark_portfolio');
Route::get('/tm_dashbord', 'FrontEndController@tm_index');
Route::get('/new_tradmark', 'FrontEndController@add_tradmark');
Route::get('/tradmark_summary', 'FrontEndController@tradmark_summary');
Route::post('/new_tradmark/save', 'AddTradmarkController@Tradmarksave');
Route::get('/edit_summary/{id}', 'AddTradmarkController@edit');
Route::post('/tradmark/update', 'AddTradmarkController@update');
Route::get('/tradmark/{id}/show', 'AddTradmarkController@show_tradmark');
Route::post('update/status', 'AddTradmarkController@update_status');
Route::get('unit/show', 'AddTradmarkController@ShowUnit');

resources/views/applicant_cat/create.blade.php
@include('include.header')
    <style>
        .card{
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        }
    </style>
    <div class="page-wrapper">
        <div class="container-fluid">
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h4 class="text-themecolor">Category Of Application | <a href="{{ url('applicant_category') }}" >Go Back <i class="fa fa-arrow-circle-left"></i></a> </h4>
                </div>
                <div class="col-md-7 align-self-center text-right">
                    <div class="d-flex justify-content-end align-items-center">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                            <li class="breadcrumb-item active">Add Category of Applicant</li>
                        </ol>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('applicant_category.store') }}" method="POST" data-parsley-validate = '' enctype="multipart/form-data">
                    @csrf
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="form-group">
                                    <label>Category Name *:</label>
                                    <input type="text" name="name" class="form-control" required="">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="text-center">
                                    <input type="submit" name="submit" value="Add Category of Applicant" class="btn btn-success">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@include('include.footer')

resources/views/applicant_cat/edit.blade.php
@include('include.header')
    <style>
        .card{
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        }
    </style>
    <div class="page-wrapper">
        <div class="container-fluid">
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h4 class="text-themecolor">Edit Category Of Application | <a href="{{ url('applicant_category') }}" >Go Back <i class="fa fa-arrow-circle-left"></i></a> </h4>
                </div>
                <div class="col-md-7 align-self-center text-right">
                    <div class="d-flex justify-content-end align-items-center">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                        </ol>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    {!! Form::model($app,['route' => ['applicant_category.update',$app->id], 'data-parsley-validate' => '', 'method' => 'PUT']) !!}
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="form-group">
                                    {!! Form::label('name', 'Category Name*:') !!}
                                    {!! Form::text('name', null, ['class' => 'form-control','required' => '']) !!}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="text-center">
                                    {!! Form::submit('submit', ['class' => 'btn btn-success']) !!}
                                </div>
                            </div>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@include('include.footer')

resources/views/applicant_cat/index.blade.php
@include('include.header')
    <style>
        .card{
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        }
    </style>
    <div class="page-wrapper">
        <div class="container-fluid">
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h4 class="text-themecolor">Category of Applicant | <a href="{{ url('patent_master') }}" >Go Back <i class="fa fa-arrow-circle-left"></i></a> </h4>
                </div>
                <div class="col-md-7 align-self-center text-right">
                    <div class="d-flex justify-content-end align-items-center">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                            <li class="breadcrumb-item active">Category of Applicant</li>
                        </ol>
                        <a  href="{{action('CategoryApplicantController@create')}}" class="btn btn-info d-none d-lg-block m-l-15"><i class="fa fa-plus-circle"></i> Add Category of Applicant</a>
                    </div>
                </div>
            </div>
            @if ($message = Session::get('success'))
                <div class="alert alert-success alert-rounded" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    {{ $message }}
                </div>
            @endif
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="myTable" class="table table-bordered" data-order='[[ 0, "desc" ]]' data-page-length='50'>
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($cats as $cat)
                                    <tr>
                                        <td>{{ $cat->id }}</td>
                                        <td>{{ $cat->name }}</td>
                                        <td>
                                            <a href="{{ route('applicant_category.edit', $cat->id) }}" class="btn btn-success">Edit</a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@include('include.footer')