routes/web.php
Route::get('/add_tradmark/{id}/update_status', 'FrontEndController@status_create');
Route::post('/status/submit', 'AddTradmarkController@insert_status');
Route::get('/status/{id}/edit', 'FrontEndController@status_edit');
// Route::post('status/updated', 'AddTradmarkController@update_insert_status');
Route::get('/tm_reports', 'AddTradmarkController@tm_reports');
Route::get('test', 'FrontEndController@test');
Route::get('/support', 'AddTradmarkController@support');
Route::post('/tm_portfolio', 'AddTradmarkController@search');
Route::post('/tradmark/search', 'AddTradmarkController@search');
Route::post('/tm_reports', 'AddTradmarkController@tm_reports_search');
Route::get('status_table/{modal}', 'AddTradmarkController@dataShow');
Route::get('/action/{id}/license', 'AddTradmarkController@actionitem');
Route::post('action/submit', 'AddTradmarkController@actionitemsave');
Route::get('license/{id}/edit', 'AddTradmarkController@actionitemedit');
Route::post('/license/update', 'AddTradmarkController@actionitemupdate');
// Route::get('tradmark/pdf', 'AddTradmarkController@printPDF');
// Route::get('tradmark/{id}/pdf', [ 'as' => 'tradmark.printpdf', 'uses' => 'AddTradmarkController@printPDF']);
Auth::routes();
// Auth::routes(['login'=> false]);

// Route::get('/home', 'HomeController@index')->name('home');
Route::redirect('register', 'login', 301);
Route::redirect('home', 'dashbord', 301);
Route::get('events/calendar', 'AddTradmarkController@eventsCalendar')->name("events.update");
Route::get('modal-data/piechart/{id}', 'FrontEndController@modaldatapiechart');
Route::get('modal-datas/piechart/{id}', 'FrontEndController@modaldataspiechart');
Route::get('modal-data2/piechart/{id}', 'FrontEndController@modaldata2piechart');
Route::get('modal-data3/piechart/{id}', 'FrontEndController@modaldata3piechart');
Route::get('modal-data4/piechart/{id}', 'FrontEndController@modaldata4piechart');
Route::get('modal-data5/piechart/{id}', 'FrontEndController@modaldata5piechart');
Route::get('modal-data6/piechart/{id}', 'FrontEndController@modaldata6piechart');
Route::get('modal-data7/piechart/{id}', 'FrontEndController@modaldata7piechart');
Route::get('modal-data11/piechart/{id}', 'FrontEndController@modaldata11piechart');
Route::get('modal-data/barchart/{id}', 'FrontEndController@modalbarchart');
Route::get('modalge/{id}','AddBrandController@modalgeodata');
Route::get('modal-datap/piechart/{id}', 'PatentController@modlp');
Route::get('modal-dataps/piechart/{id}', 'PatentController@modlps');
// Route::get('view/all', 'AddTradmarkController@viewall');
// Route::get('tradmark/search', 'AddTradmarkController@tradmark_search');
// Route::get('/show_license', 'AddTradmarkController@show_license');
// Route::get('/edit/{id}/edit_license', 'AddTradmarkController@edit_license');
// Route::post('license/update', 'AddTradmarkController@update_license');
Route::resource('notices','LitigationNoticesController');
Route::resource('/summary','LitigationSummaryController');
Route::get('litigation_master','LitigationMasterController@index');
Route::resource('liti_type','LitiTypeController');
Route::resource('area_exp','AraeExController');
Route::resource('law_firm','LawFirmController');
Route::resource('ex_counsel','ExtCounselController');
Route::resource('stages','StagesController');
Route::resource('legal_not','LegalNoticeController');
Route::resource('Court_list','CourtListController');
Route::resource('advoc','AdvocateController');
Route::resource('currenc','CurrencController');
Route::post('/noticess', 'LitigationNoticesController@search');
Route::post('/summarys', 'LitigationSummaryController@search');
Route::resource('hearing','LitiHearingController');
Route::resource('completion','CompletionController');
Route::get('hearing/create/{sum}','HearingController@create');
Route::post('hearing/submit','HearingController@store');
Route::get('hearing/edit/{id}','HearingController@edit');
Route::post('headering/store/{id}','HearingController@update');
Route::get('liti_doc/create/{id}','LitiDocController@create');
Route::post('liti_doc/submit','LitiDocController@store');
Route::resource('product','ProductController');
Route::get('notsta/create/{id}','NoticeStatController@create');
Route::post('notsta/submit','NoticeStatController@store');
Route::resource('des_mas','DesignMasterController');
Route::resource('trade_mas','TradeMasterController');
Route::resource('sections','DesignClassController');
Route::get('agent_fee/trademark/{id}','AgentFeeController@trade_fee');
Route::post('agent_fee/save','AgentFeeController@trade_save');
Route::resource('/trademark_fees','TradeMarkGovFeesController');
Route::get('/findtype','ChildController@findtype');
Route::get('/findfee','ChildController@findfee');
Route::get('/findagent','ChildController@findagent');
Route::get('/findnat','ChildController@findnat');
Route::get('/finduser','ChildController@finduser');
Route::get('classdes','ChildController@classdes');
Route::resource('/trade_class','TradeClassController');
Route::resource('licenseIn','LicenceInController');
Route::get('trlicense/{id}','TrLicInController@tr_index');
Route::post('trlicense/save','TrLicInController@tr_save');
Route::get('trin/{id}','TrLicInController@tr_edit');
Route::post('trin/save/{id}','TrLicInController@tr_edit_save');
Route::get('cr_lice','LicenceInController@cr_lice');
Route::get('des_lice','LicenceInController@des_lice');
Route::get('pat_lice','LicenceInController@pat_lice');
Route::resource('licenseOut','LicenceOutController');
Route::get('cr_liceo','LicenceOutController@cr_liceo');
Route::get('des_liceo','LicenceOutController@des_liceo');
Route::get('pat_liceo','LicenceOutController@pat_liceo');
Route::get('trlicense/out/{id}','TrLicOutController@tr_index');
Route::post('trlicense/out/save','TrLicOutController@tr_save');
Route::get('trout/{id}','TrLicOutController@tr_edit');
Route::post('trout/save/{id}','TrLicOutController@tr_edit_save');
Route::resource('assignOut','AssignOutController');
Route::get('cr_assout','AssignOutController@cr_assout');
Route::get('des_assout','AssignOutController@des_assout');
Route::get('pat_assout','AssignOutController@pat_assout');
Route::resource('assignIn','AssignInController');
Route::get('cr_assin','AssignInController@cr_assin');
Route::get('des_assin','AssignInController@des_assin');
Route::get('pat_assin','AssignInController@pat_assin');
Route::get('trass/in/{id}','TrAssInController@tr_index');
Route::post('trass/in/save','TrAssInController@tr_save');
Route::get('asin/{id}','TrAssInController@tr_edit');
Route::post('asin/save/{id}','TrAssInController@tr_edit_save');
Route::get('trass/out/{id}','TradAssOutController@tr_index');
Route::post('trass/out/save','TradAssOutController@tr_save');
Route::get('asout/{id}','TradAssOutController@tr_edit');
Route::post('asout/save/{id}','TradAssOutController@tr_edit_save');
Route::resource('leads','LeadController');
Route::get('lead_gen','leadGenController@create');
Route::post('lead_save','leadGenController@save');
Route::resource('country','CountryController');
Route::resource('state','StateController');
Route::get('/findstate','ChildController@findStates');
Route::get('/findcity','ChildController@findcity');
Route::get('/findprod','ChildController@findprod');
Route::get('/trademark/update_status/edit/{id}','FrontEndController@edit_status');
Route::post('edit/status/submit','AddTradmarkController@update_insert_status');
Route::get('images/{image}/delete/{id}','DeleteImageController@tradeimg');
Route::get('imagess/{image}/delete/{id}','DeleteImageController@tradestate');
Route::get('imagesss/{image}/delete/{id}','DeleteImageController@tradeslogo');
Route::get('images/delete/{image}/{id}','DeleteImageController@updateImg');
Route::get('imagesh/delete/{image}/{id}','DeleteImageController@updateImgh');
Route::get('update_status/delete/{id}','DeleteListController@trade_status');
Route::get('imagesc/delete/{image}/{id}','DeleteImageController@copyimg');
Route::get('imagesc/deletec/{image}/{id}','DeleteImageController@copyimgd');
Route::get('imagesc/deleteca/{image}/{id}','DeleteImageController@copyimgda');
Route::get('imaged/delete/{image}/{id}','DeleteImageController@designimgda');
Route::get('imagesd/delete/{image}/{id}','DeleteImageController@designimgdas');
Route::get('imagesds/delete/{image}/{id}','DeleteImageController@designimgdass');
Route::get('imagesdsd/delete/{image}/{id}','DeleteImageController@designimgdassd');
Route::get('imagi/delete/{image}/{id}','DeleteImageController@investimg');
Route::get('design/images/delete/{image}/{id}','DeleteImageController@designimgd');
Route::get('designcor/images/delete/{image}/{id}','DeleteImageController@designimgcor');
Route::get('copy/delete/{image}/{id}','DeleteImageController@cuimg');
Route::get('enf/delete/{image}/{id}','DeleteImageController@enfimg');
Route::get('branddashboard','DashboardController@brand');
Route::get('designdashboard','DashboardController@design');
Route::get('copydashboard','DashboardController@copy');
Route::get('patentdashboard','DashboardController@patent');
Route::get('litidashboard','DashboardController@liti');
Route::get('trad_master','MasterController@trade');
Route::get('common_master','MasterController@common');
Route::get('patent_master','MasterController@patent');
Route::get('brand_master','MasterController@brand');
Route::get('copy_master','MasterController@copy');
Route::get('notice/delete/{image}/{id}','DeleteImageController@noticeimg');
Route::get('/summary/hearing/{id}','HearingController@hearing');
Route::get('/summary/documents/{id}','LitiDocController@index');
Route::get('/summary/fees/{id}','FessController@index');
Route::get('summary/completion/{id}','CompletionController@comple');
Route::get('counsel-fees/{id}','FessController@counsel');
Route::post('counsel_fees/submit','FessController@save');
Route::get('summary/counsel-fee/edit/{id}','FessController@edit');
Route::post('counsel_fees_edit/submit','FessController@edit_save');

resources/views/court/create.blade.php
@include('include.header')
<style>
    .card{
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    }
</style>
   <!-- ============================================================== -->
        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
              <div class="row page-titles">
                    <div class="col-md-5 align-self-center">
                        <h4 class="text-themecolor">Court | <a href="{{route('Court_list.index')}}" >Go Back <i class="fa fa-arrow-circle-left"></i></a> </h4>
                    </div>
                    <div class="col-md-7 align-self-center text-right">
                        <div class="d-flex justify-content-end align-items-center">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{action('FrontEndController@index')}}">Home</a></li>
                                <li class="breadcrumb-item active">Court</li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- ============================================================== -->
                <!-- End Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Info box -->
                <!-- ============================================================== -->

                @include('include.message')
                <div class="row">
                <div class="col-md-12">
                  <div class="card">
                  <div class="card-body">
                    {!! Form::open(['route' => 'Court_list.store','data-parsley-validate' => '','method' => 'POST']) !!}
                    <div class="row">
                      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 form-group">
                        {{ Form::label('name','Court:') }}
                        {{ Form::text('name',null,['class' => 'form-control','required' => '']) }}
                      </div>
                      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
                        {{ Form::submit('Submit',['class' => 'btn btn-success']) }}
                      </div>
                    </div>
                    {!! Form::close() !!}
                  </div>
                </div>
                </div>

                </div>





            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
            <!-- ============================================================== -->
        </div>
  @include('include.footer')

resources/views/court/edit.blade.php
@include('include.header')
<style>
    .card{
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    }
</style>

    <!-- ============================================================== -->
        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
              <div class="row page-titles">
                    <div class="col-md-5 align-self-center">
                        <h4 class="text-themecolor">Court | <a href="{{route('Court_list.index')}}" >Go Back <i class="fa fa-arrow-circle-left"></i></a> </h4>
                    </div>
                    <div class="col-md-7 align-self-center text-right">
                        <div class="d-flex justify-content-end align-items-center">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{action('FrontEndController@index')}}">Home</a></li>
                                <li class="breadcrumb-item active">Court</li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- ============================================================== -->
                <!-- End Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Info box -->
                <!-- ============================================================== -->

                @include('include.message')
                <div class="row">
                <div class="col-md-12">
                  <div class="card">
                  <div class="card-body">
                    {!! Form::model($liti,['route' => ['Court_list.update',$liti->id],'data-parsley-validate' => '','method' => 'PUT']) !!}
                    <div class="row">
                      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 form-group">
                        {{ Form::label('name','Court:') }}
                        {{ Form::text('name',null,['class' => 'form-control','required' => '']) }}
                      </div>
                      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
                        {{ Form::submit('Submit',['class' => 'btn btn-success']) }}
                      </div>
                    </div>
                    {!! Form::close() !!}
                  </div>
                </div>
                </div>

                </div>





            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
            <!-- ============================================================== -->
        </div>
  @include('include.footer')

resources/views/court/index.blade.php
@include('include.header')
<style>
    .card{
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    }
</style>
   <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
                <div class="row page-titles">
                    <div class="col-md-5 align-self-center">
                        <h4 class="text-themecolor">Court List | <a href="{{action('LitigationMasterController@index')}}" >Go Back <i class="fa fa-arrow-circle-left"></i></a> </h4>
                    </div>
                    <div class="col-md-7 align-self-center text-right">
                        <div class="d-flex justify-content-end align-items-center">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{action('FrontEndController@index')}}">Home</a></li>
                                <li class="breadcrumb-item active">Court List</li>
                            </ol>
                            <a  href="{{route('Court_list.create')}}" class="btn btn-info d-none d-lg-block m-l-15"><i class="fa fa-plus-circle"></i> Add</a>
                        </div>
                    </div>
                </div>
                <!-- ============================================================== -->
                <!-- End Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Info box -->
                <!-- ============================================================== -->


                   @if ($message = Session::get('success'))
      <div class="alert alert-success alert-rounded" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  {{ $message }}
</div>
@endif

                    <!-- Column -->
                   <div class="col-md-12">
                     <div class="card">
                            <div class="card-body">
                                <div class="table-responsive m-t-40">
                                    <table id="myTable" class="table table-bordered table-striped">
                                        <thead>
                                        <tr>
                                          <th>Sr No</th>
                                          <th>Court Name</th>
                                          <th>Edit</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                          @foreach($litis as $liti)
                                          <tr>
                                          <td>{{ $no++ }}</td>
                                          <td>{{ $liti->name }}</td>
                                          <td>
                                            <a href="{{ route('Court_list.edit',$liti->id) }}" class="btn btn-danger">Edit</a>
                                            {{-- <a href="{{ route('Court_list.destroy',$liti->id) }}" class="btn btn-warning">Delete</a> --}}
                                          </td>
                                        </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>





                </div>





            </div>
                   </div>
        </div>
  @include('include.footer')